### ISSUE TITLE
pkg install failed in octave 8.2

### ISSUE THREAD

**Issue by linuxbckp** [pr0m1th3as/tensorflow#1]
>> pkg install "https://github.com/pr0m1th3as/tensorflow/archive/refs/tags/release-0.1.1.tar.gz"
g++: warning: Files\GNUOCT~1\OCTAVE~1.0\mingw64/include: linker input file unused because linking not done
g++: error: Files\GNUOCT~1\OCTAVE~1.0\mingw64/include: linker input file not found: No such file or directory
make: *** [Makefile:5: all] Error 1
make: Entering directory '/tmp/oct-r8y6kS/tensorflow-release-0.1.1/src'
E:/Program\ Files/GNUOCT~1/OCTAVE~1.0/mingw64/bin/mkoctfile-8.2.0.exe tensorflow.cc \
               OCT_TF_Buffer.cc \
               OCT_TF_DataType.cc \
               OCT_TF_Graph.cc \
               OCT_TF_Input.cc \
               OCT_TF_Operation.cc \
               OCT_TF_OperationDescription.cc \
               OCT_TF_Output.cc \
               OCT_TF_Status.cc \
               OCT_TF_String.cc \
               OCT_TF_Tensor.cc \
               -ltensorflow
make: Leaving directory '/tmp/oct-r8y6kS/tensorflow-release-0.1.1/src'

error: pkg: error running 'make' for the tensorflow package
error: called from
    configure_make at line 117 column 9
    install at line 202 column 7
    pkg at line 619 column 9

**Comment by pr0m1th3as** [comment]
The `tensorflow` package can only be installed on linux platforms with the libtensorflow C API library v2.15.0 installed.

**Comment by linuxbckp** [comment]
I changed to Fedora 40, downloaded tensorflow C API and build passed.
